ingress:
  enabled: true
  hosts:
    - blackbox-exporter.local.dev
  tls:
    - hosts:
        - blackbox-exporter.local.dev
      secretName: blackbox-exporter-tls  
extraArgs:
  - --log.level=info  
config:
  modules:
    http_2xx:
      prober: http
      timeout: 10s
      http:
        valid_status_codes: 
          - 200
          - 302
        valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        preferred_ip_protocol: ip4
        ip_protocol_fallback: true
        tls_config:
          insecure_skip_verify: true
    tcp_connect:
      prober: tcp
      tcp:    
        preferred_ip_protocol: ip4
        query_response:
          - send: "GET / HTTP/1.1"
          - send: "Host: blackbox-exporter"
          - send: "\n"
          - send: "\n"
          - expect: "HTTP/1.1 302 Found"
         