ingress:
  enabled: true
  hosts:
    - blackbox-exporter.local.dev  
extraArgs:
  - --log.level=info
  - --log.format=json
config:
  modules:
    http_2xx:
      prober: http
      timeout: 10s
      http:
        valid_status_codes: 
          - 200
          - 302
        valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        preferred_ip_protocol: ip4
        ip_protocol_fallback: true
        tls_config:
          insecure_skip_verify: true