apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: blackbox-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  groups:
  - name: blackbox-alerts
    rules:
    - alert: UrlDown
      expr: probe_success == 0
      for: 1m
      labels:
        severity: critical
        alertgroup: UrlMonitoring
      annotations:
        message: "URL {{ $labels.instance }} not reachable for over 1 minute."
    - alert: CertExpiringSoon
      expr: floor((probe_ssl_earliest_cert_expiry - time()) / 86400) < 25
      for: 1m
      labels:
        severity: critical
        alertgroup: CertExpiryMonitoring
      annotations:
        message: "Certificate for {{ $labels.instance }} expires in {{ $value }} days."
    # This alert should be inhibited by UrlDown in the Alertmanager config.
    # Right now, prometheus-operator doesn't allow it to be configured together with the alert.
    - alert: HighDowntime
      expr: avg_over_time(probe_success[15m]) < 0.75
      for: 10m
      labels:
        severity: critical
        alertgroup: UrlMonitoring
      annotations:
        message: "URL {{ $labels.instance }} has under 75% uptime for the past 10 minutes."