## nginx configuration
## Ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/index.md
##
controller:
  
  hostPort:
    enabled: true
    enableHttp: true
    enableHttps: true

    ports:
      http: 80
      https: 443
    
    targetPorts:
      http: http
      https: https
  
  service:
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443

  admissionWebhooks:
    enabled: false
      
  metrics:
    enabled: true
    
    serviceMonitor:
      enabled: true
      namespaceSelector:
        any: true