{
 "title": "Logs per Namespace",
 "description": "Shows container logs per namespace",
 "tags": [ "elk" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.namespace_name\"}"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "{\"find\": \"terms\", \"field\": \"kubernetes.pod_name\", \"query\": \"kubernetes.namespace_name:$namespace\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespaces",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.namespace_name",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs per Pod in $namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "kubernetes.pod_name",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "kubernetes.namespace_name:$namespace",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs per Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "kubernetes.namespace_name",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "2",
       "settings": {
        "interval": "auto",
        "min_doc_count": 0,
        "offset": "",
        "trimEdges": null
       },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Logs in ${namespace} namespace / ${pod} pod",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.namespace_name:$namespace AND kubernetes.pod_name:$pod",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}