{
 "title": "Terminated Pods",
 "description": "Shows logs of terminated pods",
 "tags": [ "elk" ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "reason",
    "label": "reason",
    "query": "label_values(kube_pod_container_status_terminated_reason,reason)"
   },
   {
    "name": "uid",
    "label": "uid",
    "query": "query_result( sum by(pod,reason,namespace,uid) (kube_pod_container_status_terminated_reason{pod=~\".*\",reason=\"$reason\"} * on (pod,namespace) group_left(uid) kube_pod_info > 0) )"
   }
  ]
 },
 "panels": [
  {
   "title": "Terminated Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(pod,reason,namespace,uid) (kube_pod_container_status_terminated_reason{pod=~\".*\",reason=\"$reason\"} * on (pod,namespace) group_left(uid) kube_pod_info > 0)  "
    }
   ]
  },
  {
   "title": "Terminated Reason",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " sum by (reason) (kube_pod_container_status_terminated_reason{pod=~\".*\"} ) > 0   "
    }
   ]
  },
  {
   "title": "Logs terminated pod",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "logs"
      }
     ],
     "query": "kubernetes.pod.uid.keyword:\"$uid\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}